# Generated by Django 3.0.5 on 2023-02-15 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orcheBert', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.TextField(blank=True, null=True)),
                ('last_name', models.TextField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=191, null=True, unique=True)),
                ('password', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Humming_MIDI',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hummingFile_path', models.CharField(blank=True, max_length=191, null=True)),
                ('midiFile_path', models.CharField(blank=True, max_length=191, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orcheBert.Users')),
            ],
        ),
        migrations.CreateModel(
            name='OrchestraMIDI',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file_path', models.CharField(blank=True, max_length=191, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('humming_midi_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orcheBert.Humming_MIDI')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orcheBert.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('orchestraMIDI_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orcheBert.OrchestraMIDI')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orcheBert.Users')),
            ],
        ),
    ]
