# Generated by Django 3.0.5 on 2023-02-15 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orcheBert', '0002_favorite_humming_midi_orchestramidi_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='orchestraMIDI_id',
            new_name='orchestraMIDI',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='orchestramidi',
            old_name='humming_midi_id',
            new_name='humming_midi',
        ),
    ]
