# Generated by Django 3.0.5 on 2023-02-15 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcheBert', '0003_auto_20230215_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='orchestramidi',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
